// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250128191444_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Stocks Table
            modelBuilder.Entity("Backend.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stocks");
                });

            // Users Table
            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Property<string>("Email")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(200)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<string>("Email"));

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                  

                    b.Property<int>("Balance")
                        .IsRequired()
                           .HasColumnType("int");

                    b.HasKey("Email");

                    b.ToTable("Users");
                });

            // Trades Table
            modelBuilder.Entity("Backend.Models.Trade", b =>
                {

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<DateTime>("TradeDate"));

                    b.Property<string>("UserEmail")
                     .HasColumnType("nvarchar(100)");


                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TradeDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TradeDate");

                    b.HasIndex("UserEmail");

                    b.ToTable("Trades");
                });

            // Foreign Key Relationships
            modelBuilder.Entity("Backend.Models.Trade", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("Trades")
                        .HasForeignKey("UserEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            // Navigation Properties
            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Navigation("Trades");
                });

#pragma warning restore 612, 618
        }
    }
}
