version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - qdrant
      - ollama
    networks:
      - agent-network

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - agent-network

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - agent-network

networks:
  agent-network:

volumes:
  qdrant_data:
  ollama_data: